[ADMINAPI-993] Fixing Token Permissions issues
Ed-Fi-Alliance-OSS/AdminAPI-2.x pull request #110
Opened 2024-05-02 18:14 UTC by msilesgap

2024-05-02 21:43 UTC, stephenfuqua commented on .github/workflows/scorecard.yml
I'm confused - this repository already has a `scorecard.yml` in the `main` branch.

https://github.com/Ed-Fi-Alliance-OSS/AdminAPI-2.x/blob/main/.github/workflows/scorecard.yml

You might need to rebase this pull request from `origin/main`.

2024-05-02 22:10 UTC, msilesgap commented on .github/workflows/scorecard.yml
Could you check again?

2024-05-03 01:35 UTC, stephenfuqua approved these changes

2024-05-03 01:36 UTC, stephenfuqua requested changes
Please update by signing your commits.

2024-05-03 13:29 UTC, stephenfuqua approved these changes

2024-05-03 13:29 UTC, merged