ADMINAPI-1077 Add Get/Post endpoints for healthchecks
Ed-Fi-Alliance-OSS/AdminAPI-2.x pull request #177
Opened 2024-10-30 02:25 UTC by dfernandez-gap

2024-11-01 22:03 UTC, jagudelo-gap requested changes
@DavidJGapCR @jleiva-gap @dfernandez-gap @ricardogamboagap 
We should include some e2e, just a simple validation of the endpoints. If it is complicated, we have to create a ticket for that.

We have to consider how to include or execute the scripts in the database automatically (if flag is enabled), maybe the runtime migration can help us by the time being, but it doesn't seem to be the best approach based on Microsoft recommendation. I would prefer scripts but you could find a better approach.

https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/applying?tabs=dotnet-core-cli#apply-migrations-at-runtime

2024-11-01 22:57 UTC, dfernandez-gap commented on Application/EdFi.Ods.AdminApi/Program.cs
> +if (builder.Configuration.GetValue<bool>("AppSettings:EnableAdminConsoleAPI"))
Added change as requested

2024-11-01 22:58 UTC, dfernandez-gap commented on Application/EdFi.Ods.AdminApi/Program.cs
> +    ServiceRegistration.AddRepositories(builder.Services);
Added change as requested

2024-11-01 22:58 UTC, dfernandez-gap commented on Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/Services/HealthChecks/Queries/GetHealthCheckQuery.cs
> +        ?? throw new Exception($"Not found {nameof(HealthCheck)} for Tenant Id: {tenantId}");
Added change as requested

2024-11-04 17:30 UTC, DavidJGapCR commented on Application/EdFi.Ods.AdminApi.AdminConsole/Infrastructure/Services/HealthChecks/Queries/GetHealthCheckQuery.cs
> +        ?? throw new Exception($"Not found {nameof(HealthCheck)} for Tenant Id: {tenantId}");
https://edfi.atlassian.net/browse/ADMINAPI-1084
Added a ticket to cover e2e tests.

2024-11-05 15:43 UTC, jagudelo-gap approved these changes

2024-11-05 15:44 UTC, merged