[ADMINAPI-1085]: Create a shared library code for Admin API
Ed-Fi-Alliance-OSS/AdminAPI-2.x pull request #194
Opened 2024-11-25 19:51 UTC by jleiva-gap

- Create EdFi.Ods.AdminApi.Common library
- Update references between projects
- Move common classes to the new library
- Remove redundant code
- Update nuget packages to remove vulnerabilities

2024-11-27 16:19 UTC, jasonh-edfi approved these changes
Files reviewed and approved for the refactor

2024-11-27 17:52 UTC, jagudelo-gap requested changes

2024-11-27 17:52 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApi.Common/Infrastructure/Helpers/FeaturesExtensions.cs
> +    public static List<IFeature> GetFeatures2()
Is this name correct "GetFeatures2"? It seems this is not required

2024-11-28 14:35 UTC, jagudelo-gap approved these changes

2024-11-28 14:35 UTC, merged