[ADMINAPI-1107]  Update Admin API Admin Console endpoints to have same authorization
Ed-Fi-Alliance-OSS/AdminAPI-2.x pull request #206
Opened 2024-12-20 20:13 UTC by ricardogamboagap

2024-12-20 20:36 UTC, jagudelo-gap requested changes

2024-12-20 20:36 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApi/Infrastructure/Security/SecurityExtensions.cs
> +                var oidcIssuer = configuration.Get<string>("Authentication:OIDC:Authority");
@jleiva-gap 
Should we add the statement
`options.RequireHttpsMetadata = configuration.Get<bool>("Authentication:OIDC:RequireHttpsMetadata");` 
here?

2024-12-20 20:36 UTC, jagudelo-gap commented on Application/EdFi.Ods.AdminApi/Infrastructure/Security/SecurityExtensions.cs
> +using Polly;
We don't need it, please remove it.

2024-12-20 22:48 UTC, jagudelo-gap approved these changes

2024-12-23 22:08 UTC, jleiva-gap commented on Application/EdFi.Ods.AdminApi/Infrastructure/Security/SecurityExtensions.cs
>                  .RequireClaim(OpenIddictConstants.Claims.Scope, SecurityConstants.Scopes.AdminApiFullAccess)
Use 
```
.RequireAssertion(context =>
                        context.User.HasClaim(c => c.Type == OpenIddictConstants.Claims.Scope && c.Value.Contains(SecurityConstants.Scopes.AdminApiFullAccess))
```

2024-12-23 22:39 UTC, jleiva-gap approved these changes

2024-12-23 22:40 UTC, merged